server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
#    username: adam
#    password: my2018
#    testWhileIdle: true
#    validationQuery: SELECT 1

spring:
  h2:
    console:
      enabled: true
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true

hello.foo:
  - c

management:
  endpoints:
    web:
      exposure:
        include: "*"

