server:
  port: 8808

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: adam
    password: my2018
    testWhileIdle: true
    validationQuery: SELECT 1