CREATE TABLE `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  `username` varchar(64) NOT NULL UNIQUE DEFAULT '' COMMENT '用户名',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `event` (
  `event_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '活动D',
  `event_title` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '活动标题',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) DEFAULT CHARSET=utf8 COMMENT='活动表';